/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import clases.GestionEscritorios;
import clases.GestionTickets;

/**
 *
 * @author Dell Laptop
 */

public class AccesoAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form AccesoAdministrador
     */
    public AccesoAdministrador(String t) {
        initComponents();
        this.setLocationRelativeTo(null);//colocar en el centro
        Interfaz usuario= new Interfaz();
        BienvenidaTxt.setText("Bienvenido "+t);
        System.out.print(usuario.nuevoUsuario.getUser());
    }
    
        GestionEscritorios crearEscritorio = new GestionEscritorios();
        CrearTicket crearTicket= new CrearTicket();


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BienvenidaTxt = new javax.swing.JLabel();
        BtnCrearUsuario = new javax.swing.JButton();
        BtnEliminarUsuario = new javax.swing.JButton();
        BtnModUsuario = new javax.swing.JButton();
        BtnCrearEscritorio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnEliminarEscritorio = new javax.swing.JButton();
        BtnCrearEscritorio1 = new javax.swing.JButton();
        BtnModUsuario1 = new javax.swing.JButton();
        BtnEliminarUsuario1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        BienvenidaTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BienvenidaTxt.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BienvenidaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BienvenidaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        BtnCrearUsuario.setText("CREAR USUARIO");
        BtnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearUsuarioActionPerformed(evt);
            }
        });

        BtnEliminarUsuario.setText("ELIMINAR USUARIO");
        BtnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarUsuarioActionPerformed(evt);
            }
        });

        BtnModUsuario.setText("MODIFICAR USUARIO");
        BtnModUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModUsuarioActionPerformed(evt);
            }
        });

        BtnCrearEscritorio.setText("CREAR ESCRITORIO");
        BtnCrearEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearEscritorioActionPerformed(evt);
            }
        });

        jButton1.setText("IMFORME DE TICKET");

        BtnEliminarEscritorio.setText("ELIMINAR ESCRITORIO");
        BtnEliminarEscritorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarEscritorioActionPerformed(evt);
            }
        });

        BtnCrearEscritorio1.setText("CREAR TICKET");
        BtnCrearEscritorio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearEscritorio1ActionPerformed(evt);
            }
        });

        BtnModUsuario1.setText("MODIFICAR TICKET");
        BtnModUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModUsuario1ActionPerformed(evt);
            }
        });

        BtnEliminarUsuario1.setText("ELIMINAR TICKET");
        BtnEliminarUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarUsuario1ActionPerformed(evt);
            }
        });

        jButton2.setText("REPORTE DIARIO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCrearUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModUsuario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCrearEscritorio1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminarEscritorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCrearEscritorio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminarUsuario1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCrearUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnModUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminarUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnCrearEscritorio)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminarEscritorio)
                .addGap(18, 18, 18)
                .addComponent(BtnCrearEscritorio1)
                .addGap(18, 18, 18)
                .addComponent(BtnModUsuario1)
                .addGap(18, 18, 18)
                .addComponent(BtnEliminarUsuario1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearUsuarioActionPerformed
        CrearUsuario crear = new CrearUsuario();
        crear.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCrearUsuarioActionPerformed

    private void BtnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarUsuarioActionPerformed
        BorrarUsuario borrar = new BorrarUsuario();
        borrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnEliminarUsuarioActionPerformed

    private void BtnModUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModUsuarioActionPerformed
        ModificarUsuario modUser = new ModificarUsuario();
        this.setVisible(false);
        modUser.setVisible(true);
    }//GEN-LAST:event_BtnModUsuarioActionPerformed

    private void BtnCrearEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearEscritorioActionPerformed

        try{
        crearEscritorio.push();
        }catch(Exception e){
            System.out.println("Ocurrio un error: "+e);    
        }
        
        
        
        
        
    }//GEN-LAST:event_BtnCrearEscritorioActionPerformed

    private void BtnEliminarEscritorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarEscritorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarEscritorioActionPerformed

    private void BtnCrearEscritorio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearEscritorio1ActionPerformed
       
        crearTicket.setVisible(true);
        
    }//GEN-LAST:event_BtnCrearEscritorio1ActionPerformed

    private void BtnModUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModUsuario1ActionPerformed

    private void BtnEliminarUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarUsuario1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ReporteDiario r = new ReporteDiario();
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccesoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccesoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccesoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccesoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidaTxt;
    private javax.swing.JButton BtnCrearEscritorio;
    private javax.swing.JButton BtnCrearEscritorio1;
    private javax.swing.JButton BtnCrearUsuario;
    private javax.swing.JButton BtnEliminarEscritorio;
    private javax.swing.JButton BtnEliminarUsuario;
    private javax.swing.JButton BtnEliminarUsuario1;
    private javax.swing.JButton BtnModUsuario;
    private javax.swing.JButton BtnModUsuario1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
